const LaptopApis = [
  {
    id: 1,
    name: "Dell XPS 13",
    price: "1,000",
    screenSize: '13.3"',
    storageCapacity: "512GB SSD",
    processor: "Intel Core i7",
    imageUrl: "https://via.placeholder.com/300x200?text=Dell+XPS+13",
    description:
      "The Dell XPS 13 is a sleek and powerful laptop featuring a 13.3\" FHD display, Intel Core i7 processor, and 512GB SSD. It's known for its compact design and high performance, making it ideal for professionals and students alike.",
    brand: "Dell",
    series: "XPS",
    type: "Ultrabook",
    processor: "Intel Core i7",
    graphics: "Intel Iris Xe",
    chipset: "Intel",
    memory: "16GB",
    memorySlots: "2",
    maxMemory: "32GB",
    storage: "512GB SSD",
    storageSupport: "M.2 PCIe NVMe",
    cardReader: "No",
    speakers: "Stereo",
    camera: "720p HD",
    microphone: "Yes",
    battery: "52Wh",
  },
  {
    id: 2,
    name: "Lenovo IdeaPad Slim 7",
    price: "800",
    screenSize: '14"',
    storageCapacity: "512GB SSD",
    processor: "Intel Core i7",
    imageUrl: "https://via.placeholder.com/300x200?text=Lenovo+IdeaPad+Slim+7",
    description:
      'The Lenovo IdeaPad Slim 7 offers a 14" display with a slim and lightweight design. It is powered by an Intel Core i7 processor and comes with a 512GB SSD, providing a balance of performance and portability.',
    brand: "Lenovo",
    series: "IdeaPad Slim",
    type: "Ultrabook",
    processor: "Intel Core i7",
    graphics: "Intel Iris Plus",
    chipset: "Intel",
    memory: "16GB",
    memorySlots: "2",
    maxMemory: "32GB",
    storage: "512GB SSD",
    storageSupport: "M.2 PCIe NVMe",
    cardReader: "Yes",
    speakers: "Stereo",
    camera: "720p HD",
    microphone: "Yes",
    battery: "60Wh",
  },
  {
    id: 3,
    name: "HP Pavilion Gaming",
    price: "1,000",
    screenSize: '15.6"',
    storageCapacity: "1TB SSD",
    processor: "AMD Ryzen 7",
    imageUrl: "https://via.placeholder.com/300x200?text=HP+Pavilion+Gaming",
    description:
      'The HP Pavilion Gaming laptop features a 15.6" display and an AMD Ryzen 7 processor. With a 1TB SSD, it delivers excellent gaming performance and ample storage for all your games and media.',
    brand: "HP",
    series: "Pavilion",
    type: "Gaming Laptop",
    processor: "AMD Ryzen 7",
    graphics: "NVIDIA GeForce GTX 1650",
    chipset: "AMD",
    memory: "16GB",
    memorySlots: "2",
    maxMemory: "32GB",
    storage: "1TB SSD",
    storageSupport: "M.2 PCIe NVMe",
    cardReader: "Yes",
    speakers: "Stereo",
    camera: "720p HD",
    microphone: "Yes",
    battery: "70Wh",
  },
  {
    id: 4,
    name: "MacBook Air M2",
    price: "999",
    screenSize: '13.6"',
    storageCapacity: "256GB/512GB SSD",
    processor: "Apple M2",
    imageUrl: "https://via.placeholder.com/300x200?text=MacBook+Air+M2",
    description:
      'The MacBook Air M2 offers a 13.6" Retina display and is powered by the Apple M2 chip. It comes with options for 256GB or 512GB SSD storage, providing a blend of power and efficiency in a thin, lightweight design.',
    brand: "Apple",
    series: "MacBook Air",
    type: "Ultrabook",
    processor: "Apple M2",
    graphics: "Apple Integrated Graphics",
    chipset: "Apple Silicon",
    memory: "8GB/16GB",
    memorySlots: "Soldered",
    maxMemory: "24GB",
    storage: "256GB/512GB SSD",
    storageSupport: "None (Fixed)",
    cardReader: "No",
    speakers: "Stereo",
    camera: "1080p FaceTime HD",
    microphone: "Yes",
    battery: "52.6Wh",
  },
  {
    id: 5,
    name: "Asus ZenBook 14",
    price: "900",
    screenSize: '14"',
    storageCapacity: "512GB SSD",
    processor: "Intel Core i7",
    imageUrl: "https://via.placeholder.com/300x200?text=Asus+ZenBook+14",
    description:
      'The Asus ZenBook 14 features a 14" display and an Intel Core i7 processor. With 512GB of SSD storage, it combines high performance with a compact, elegant design.',
    brand: "Asus",
    series: "ZenBook",
    type: "Ultrabook",
    processor: "Intel Core i7",
    graphics: "Intel Iris Xe",
    chipset: "Intel",
    memory: "16GB",
    memorySlots: "2",
    maxMemory: "32GB",
    storage: "512GB SSD",
    storageSupport: "M.2 PCIe NVMe",
    cardReader: "Yes",
    speakers: "Harman Kardon",
    camera: "720p HD",
    microphone: "Yes",
    battery: "67Wh",
  },
  {
    id: 6,
    name: "Microsoft Surface Laptop 5",
    price: "1,100",
    screenSize: '13.5"',
    storageCapacity: "512GB SSD",
    processor: "Intel Core i5/i7",
    imageUrl: "https://via.placeholder.com/300x200?text=Surface+Laptop+5",
    description:
      'The Microsoft Surface Laptop 5 boasts a 13.5" PixelSense touchscreen display and is powered by Intel Core i5 or i7 processors. It comes with 512GB SSD storage, offering a premium build and high performance.',
    brand: "Microsoft",
    series: "Surface",
    type: "Laptop",
    processor: "Intel Core i5/i7",
    graphics: "Intel Iris Xe",
    chipset: "Intel Integrated",
    memory: "8GB/16GB LPDDR4x",
    memorySlots: "Onboard",
    maxMemory: "16GB",
    storage: "512GB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "None",
    cardReader: "No",
    optical: "No",
    audioChip: "Realtek High Definition Audio",
    speakers: "Stereo speakers",
    camera: "720p HD",
    microphone: "Dual far-field",
    battery: "Up to 15 hours",
  },
  {
    id: 7,
    name: "Acer Swift 3",
    price: "799",
    screenSize: '14"',
    storageCapacity: "512GB SSD",
    processor: "AMD Ryzen 7",
    imageUrl: "https://via.placeholder.com/300x200?text=Acer+Swift+3",
    description:
      'The Acer Swift 3 is a budget-friendly laptop with a 14" display and an AMD Ryzen 7 processor. It offers 512GB SSD storage, providing a solid performance at a competitive price.',
    brand: "Acer",
    series: "Swift",
    type: "Laptop",
    processor: "AMD Ryzen 7",
    graphics: "AMD Radeon",
    chipset: "AMD Integrated",
    memory: "8GB/16GB LPDDR4",
    memorySlots: "Onboard",
    maxMemory: "16GB",
    storage: "512GB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "None",
    cardReader: "No",
    optical: "No",
    audioChip: "Realtek Audio",
    speakers: "Stereo",
    camera: "720p HD",
    microphone: "Yes",
    battery: "Up to 12 hours",
  },
  {
    id: 8,
    name: "HP Spectre x360",
    price: "1,200",
    screenSize: '13.3"',
    storageCapacity: "512GB SSD",
    processor: "Intel Core i7",
    imageUrl: "https://via.placeholder.com/300x200?text=HP+Spectre+x360",
    description:
      'The HP Spectre x360 features a 13.3" touchscreen display with a flexible 2-in-1 design. It is powered by an Intel Core i7 processor and comes with 512GB SSD storage, offering versatility and high performance.',
    brand: "HP",
    series: "Spectre",
    type: "2-in-1 Convertible",
    processor: "Intel Core i7",
    graphics: "Intel Iris Xe",
    chipset: "Intel Integrated",
    memory: "16GB LPDDR4x",
    memorySlots: "Onboard",
    maxMemory: "16GB",
    storage: "512GB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "None",
    cardReader: "No",
    optical: "No",
    audioChip: "Bang & Olufsen",
    speakers: "Quad speakers",
    camera: "1080p FHD",
    microphone: "Yes",
    battery: "Up to 13 hours",
  },
  {
    id: 9,
    name: "Lenovo ThinkPad X1 Carbon Gen 9",
    price: "1,400",
    screenSize: '14"',
    storageCapacity: "512GB/1TB SSD",
    processor: "Intel Core i7",
    imageUrl:
      "https://via.placeholder.com/300x200?text=Lenovo+ThinkPad+X1+Carbon+Gen+9",
    description:
      'The Lenovo ThinkPad X1 Carbon Gen 9 is a durable business laptop featuring a 14" display, Intel Core i7 processor, and up to 1TB SSD storage. It is known for its robust build quality and high-end performance.',
    brand: "Lenovo",
    series: "ThinkPad",
    type: "Business Laptop",
    processor: "Intel Core i7",
    graphics: "Intel Iris Xe",
    chipset: "Intel Integrated",
    memory: "16GB LPDDR4x",
    memorySlots: "Onboard",
    maxMemory: "16GB",
    storage: "512GB/1TB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "M.2",
    cardReader: "No",
    optical: "No",
    audioChip: "Dolby Atmos",
    speakers: "Stereo",
    camera: "720p HD",
    microphone: "Yes",
    battery: "Up to 18 hours",
  },
  {
    id: 10,
    name: "Dell Inspiron 15 5000",
    price: "900",
    screenSize: '15.6"',
    storageCapacity: "256GB SSD",
    processor: "Intel Core i5",
    imageUrl: "https://via.placeholder.com/300x200?text=Dell+Inspiron+15+5000",
    description:
      'The Dell Inspiron 15 5000 is a versatile laptop with a 15.6" display, Intel Core i5 processor, and 256GB SSD storage. It provides a good balance of performance and affordability for everyday tasks.',
    brand: "Dell",
    series: "Inspiron",
    type: "Laptop",
    processor: "Intel Core i5",
    graphics: "Intel Iris Xe",
    chipset: "Intel Integrated",
    memory: "8GB DDR4",
    memorySlots: "2",
    maxMemory: "16GB",
    storage: "256GB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "M.2",
    cardReader: "Yes",
    optical: "No",
    audioChip: "Waves MaxxAudio",
    speakers: "Stereo",
    camera: "720p HD",
    microphone: "Yes",
    battery: "Up to 10 hours",
  },
  {
    id: 11,
    name: "Razer Blade 15",
    price: "1,800",
    screenSize: '15.6"',
    storageCapacity: "512GB/1TB SSD",
    processor: "Intel Core i7",
    imageUrl: "https://via.placeholder.com/300x200?text=Razer+Blade+15",
    description:
      'The Razer Blade 15 is a high-performance gaming laptop featuring a 15.6" display and Intel Core i7 processor. It comes with up to 1TB SSD storage and is known for its sleek design and powerful gaming capabilities.',
    brand: "Razer",
    series: "Blade",
    type: "Gaming Laptop",
    processor: "Intel Core i7",
    graphics: "NVIDIA GeForce RTX 3060/3070",
    chipset: "Intel Integrated",
    memory: "16GB DDR4",
    memorySlots: "2",
    maxMemory: "32GB",
    storage: "512GB/1TB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "M.2",
    cardReader: "No",
    optical: "No",
    audioChip: "THX Spatial Audio",
    speakers: "Stereo",
    camera: "1080p HD",
    microphone: "Yes",
    battery: "Up to 8 hours",
  },
  {
    id: 12,
    name: "Asus ROG Zephyrus G14",
    price: "1,100",
    screenSize: '14"',
    storageCapacity: "1TB SSD",
    processor: "AMD Ryzen 9",
    imageUrl: "https://via.placeholder.com/300x200?text=Asus+ROG+Zephyrus+G14",
    description:
      'The Asus ROG Zephyrus G14 is a compact gaming laptop with a 14" display and AMD Ryzen 9 processor. It features 1TB SSD storage, delivering exceptional gaming performance in a portable form factor.',
    brand: "Asus",
    series: "ROG Zephyrus",
    type: "Gaming Laptop",
    processor: "AMD Ryzen 9",
    graphics: "NVIDIA GeForce RTX 3060",
    chipset: "AMD Integrated",
    memory: "16GB DDR4",
    memorySlots: "2",
    maxMemory: "32GB",
    storage: "1TB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "M.2",
    cardReader: "No",
    optical: "No",
    audioChip: "Dolby Atmos",
    speakers: "Stereo",
    camera: "No",
    microphone: "Yes",
    battery: "Up to 10 hours",
  },
  {
    id: 13,
    name: "Apple MacBook Pro 16",
    price: "2,400",
    screenSize: '16"',
    storageCapacity: "512GB/1TB SSD",
    processor: "Apple M1 Pro/M1 Max",
    imageUrl: "https://via.placeholder.com/300x200?text=MacBook+Pro+16",
    description:
      'The Apple MacBook Pro 16 offers a stunning 16" Retina display and is powered by the Apple M1 Pro or M1 Max chip. With up to 1TB SSD storage, it is designed for professionals needing extreme performance.',
    brand: "Apple",
    series: "MacBook Pro",
    type: "Laptop",
    processor: "Apple M1 Pro/M1 Max",
    graphics: "Integrated 16/32-core GPU",
    chipset: "Apple Silicon",
    memory: "16GB/32GB/64GB",
    memorySlots: "Onboard",
    maxMemory: "64GB",
    storage: "512GB/1TB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "None",
    cardReader: "SDXC",
    optical: "No",
    audioChip: "Apple Custom",
    speakers: "Six-speaker system",
    camera: "1080p FHD",
    microphone: "Studio-quality",
    battery: "Up to 21 hours",
  },
  {
    id: 14,
    name: "Samsung Galaxy Book Pro",
    price: "1,300",
    screenSize: '15.6"',
    storageCapacity: "512GB SSD",
    processor: "Intel Core i7",
    imageUrl:
      "https://via.placeholder.com/300x200?text=Samsung+Galaxy+Book+Pro",
    description:
      'The Samsung Galaxy Book Pro is an ultra-light laptop with a 15.6" AMOLED display, Intel Core i7 processor, and 512GB SSD storage. It is perfect for mobile professionals who need performance and portability.',
    brand: "Samsung",
    series: "Galaxy Book",
    type: "Laptop",
    processor: "Intel Core i7",
    graphics: "Intel Iris Xe",
    chipset: "Intel Integrated",
    memory: "16GB LPDDR4x",
    memorySlots: "Onboard",
    maxMemory: "16GB",
    storage: "512GB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "None",
    cardReader: "No",
    optical: "No",
    audioChip: "Realtek",
    speakers: "Stereo",
    camera: "720p HD",
    microphone: "Yes",
    battery: "Up to 17 hours",
  },
  {
    id: 15,
    name: "Google Pixelbook Go",
    price: "650",
    screenSize: '13.3"',
    storageCapacity: "128GB SSD",
    processor: "Intel Core i5",
    imageUrl: "https://via.placeholder.com/300x200?text=Google+Pixelbook+Go",
    description:
      'The Google Pixelbook Go is a sleek and affordable Chromebook with a 13.3" touchscreen, powered by an Intel Core i5 processor. It offers 128GB SSD storage and is ideal for lightweight computing tasks.',
    brand: "Google",
    series: "Pixelbook",
    type: "Chromebook",
    processor: "Intel Core i5",
    graphics: "Intel UHD Graphics",
    chipset: "Intel Integrated",
    memory: "8GB LPDDR3",
    memorySlots: "Onboard",
    maxMemory: "8GB",
    storage: "128GB SSD",
    storageSupport: "eMMC",
    storageSlot: "None",
    cardReader: "No",
    optical: "No",
    audioChip: "Realtek",
    speakers: "Stereo",
    camera: "1080p FHD",
    microphone: "Yes",
    battery: "Up to 12 hours",
  },
  {
    id: 16,
    name: "Dell XPS 13",
    price: "1,100",
    screenSize: '13.4"',
    storageCapacity: "512GB SSD",
    processor: "Intel Core i5/i7",
    imageUrl: "https://via.placeholder.com/300x200?text=Dell+XPS+13",
    description:
      'The Dell XPS 13 is known for its nearly bezel-less 13.4" InfinityEdge display, high-performance Intel Core i5/i7 processors, and up to 512GB SSD storage, making it a top choice for professionals.',
    brand: "Dell",
    series: "XPS",
    type: "Ultrabook",
    processor: "Intel Core i5/i7",
    graphics: "Intel Iris Xe",
    chipset: "Intel Integrated",
    memory: "8GB/16GB LPDDR4x",
    memorySlots: "Onboard",
    maxMemory: "16GB",
    storage: "512GB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "M.2",
    cardReader: "No",
    optical: "No",
    audioChip: "Waves MaxxAudio",
    speakers: "Stereo",
    camera: "720p HD",
    microphone: "Dual-array",
    battery: "Up to 14 hours",
  },
  {
    id: 17,
    name: "HP Envy 13",
    price: "900",
    screenSize: '13.3"',
    storageCapacity: "256GB SSD",
    processor: "Intel Core i5",
    imageUrl: "https://via.placeholder.com/300x200?text=HP+Envy+13",
    description:
      'The HP Envy 13 is a stylish and compact laptop featuring a 13.3" display, Intel Core i5 processor, and 256GB SSD storage. It is designed for users looking for a balance between design and performance.',
    brand: "HP",
    series: "Envy",
    type: "Laptop",
    processor: "Intel Core i5",
    graphics: "Intel Iris Xe",
    chipset: "Intel Integrated",
    memory: "8GB LPDDR4x",
    memorySlots: "Onboard",
    maxMemory: "8GB",
    storage: "256GB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "M.2",
    cardReader: "No",
    optical: "No",
    audioChip: "Bang & Olufsen",
    speakers: "Stereo",
    camera: "720p HD",
    microphone: "Dual-array",
    battery: "Up to 11 hours",
  },
  {
    id: 18,
    name: "Asus ZenBook 14",
    price: "950",
    screenSize: '14"',
    storageCapacity: "512GB SSD",
    processor: "Intel Core i7",
    imageUrl: "https://via.placeholder.com/300x200?text=Asus+ZenBook+14",
    description:
      'The Asus ZenBook 14 is an ultra-portable laptop featuring a 14" display and Intel Core i7 processor, with 512GB SSD storage. It offers a lightweight design with premium build quality.',
    brand: "Asus",
    series: "ZenBook",
    type: "Laptop",
    processor: "Intel Core i7",
    graphics: "Intel Iris Xe",
    chipset: "Intel Integrated",
    memory: "16GB LPDDR4x",
    memorySlots: "Onboard",
    maxMemory: "16GB",
    storage: "512GB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "M.2",
    cardReader: "MicroSD",
    optical: "No",
    audioChip: "Harman Kardon",
    speakers: "Stereo",
    camera: "720p HD",
    microphone: "Yes",
    battery: "Up to 12 hours",
  },

  {
    id: 19,
    name: "Lenovo Yoga 9i",
    price: "1,300",
    screenSize: '14"',
    storageCapacity: "512GB SSD",
    processor: "Intel Core i7",
    imageUrl: "https://via.placeholder.com/300x200?text=Lenovo+Yoga+9i",
    description:
      'The Lenovo Yoga 9i is a versatile 2-in-1 laptop with a 14" touchscreen, powered by the Intel Core i7 processor and offering 512GB SSD storage. It is ideal for creative professionals and business users.',
    brand: "Lenovo",
    series: "Yoga",
    type: "2-in-1 Convertible",
    processor: "Intel Core i7",
    graphics: "Intel Iris Xe",
    chipset: "Intel Integrated",
    memory: "16GB LPDDR4x",
    memorySlots: "Onboard",
    maxMemory: "16GB",
    storage: "512GB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "M.2",
    cardReader: "No",
    optical: "No",
    audioChip: "Dolby Atmos",
    speakers: "Rotating soundbar",
    camera: "720p HD",
    microphone: "Dual-array",
    battery: "Up to 15 hours",
  },
  {
    id: 20,
    name: "Razer Blade 15",
    price: "2,500",
    screenSize: '15.6"',
    storageCapacity: "1TB SSD",
    processor: "Intel Core i9",
    imageUrl: "https://via.placeholder.com/300x200?text=Razer+Blade+15",
    description:
      'The Razer Blade 15 is a high-performance gaming laptop featuring a 15.6" display, Intel Core i9 processor, and 1TB SSD storage. It delivers a top-tier gaming experience with its premium build and powerful hardware.',
    brand: "Razer",
    series: "Blade",
    type: "Gaming Laptop",
    processor: "Intel Core i9",
    graphics: "NVIDIA GeForce RTX 3080",
    chipset: "Intel Integrated",
    memory: "32GB DDR4",
    memorySlots: "2 x SO-DIMM",
    maxMemory: "64GB",
    storage: "1TB SSD",
    storageSupport: "NVMe SSD",
    storageSlot: "M.2",
    cardReader: "No",
    optical: "No",
    audioChip: "THX Spatial Audio",
    speakers: "Stereo",
    camera: "1080p FHD",
    microphone: "Array microphone",
    battery: "Up to 8 hours",
  },
];

export default LaptopApis;
